spring.application.name=queueease

spring.datasource.url=jdbc:mysql://localhost:3306/queueease
spring.datasource.username=root
spring.datasource.password=Jasuwanthy@05022008

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true